twtribes/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('twtribes.views',
    url(r'^(?P<tribe_slug>\w+)/$', 'tribe', {}, name='show_tribe'),
    url(r'^(?P<tribe_slug>\w+)/search/$', 'tribe_search', {}, name='show_tribe_terms'),
    url(r'^(?P<tribe_slug>\w+)/page/(?P<page_slug>[-\w]+)/$', 'tribe_search', {}, name='show_tribe_page'),
)

twtribes/models.py
from django.db import models
import re

class Tribe(models.Model):
    """A group of twitter users with a common interest or purpose"""
    
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    description = models.TextField(blank=True)
    
    master_account = models.CharField(blank=True, max_length=100)
    master_password = models.CharField(blank=True, max_length=100)
    update_interval = models.IntegerField(default=0)
    max_status = models.IntegerField(default=10)

    def __unicode__(self):
        return self.name

class InterestTerm(models.Model):
    """A term that the tribe is interested in for the live feed view"""
    
    term = models.CharField(max_length=255)
    tribe = models.ForeignKey(Tribe)
    
    def __unicode__(self):
        return self.term
        
class Page(models.Model):
    """A page of grouped interest terms for the tribe"""
    slug = models.SlugField(unique=True)
    title = models.CharField(blank=True, max_length=100)
    description = models.TextField(blank=True)

    tribe = models.ForeignKey(Tribe)
    terms = models.ManyToManyField(InterestTerm)

    def __unicode__(self):
        return self.slug

class Member(models.Model):
    """A twitter user account that's a member of a tribe"""
    
    twitter_account = models.CharField(max_length=255)
    note = models.CharField(blank=True, max_length=255)
    tribe = models.ForeignKey(Tribe)

    def __unicode__(self):
        return self.tribe.name + ": " + self.twitter_account

class ExcludedUser(models.Model):
    """Used to filter out results matching a particular twitter account"""
    
    twitter_account = models.CharField(max_length=255)
    tribe = models.ForeignKey(Tribe)
    
    def __unicode__(self):
        return self.tribe.name + ": " + self.twitter_account

class ExcludedRegexp(models.Model):
    """Used to filter out results matching a regular expression"""
    
    regexp = models.CharField(max_length=1024)
    tribe = models.ForeignKey(Tribe)
    enabled = models.BooleanField(default=True)
    
    def search(self, some_text):
        # assuming that this will use python's built in cache of regexp compilations
        if re.search(self.regexp, some_text, re.IGNORECASE):
            return True
        else:
            return False
    
    def __unicode__(self):
        return self.regexp

twtribes/templates/twtribes/tribe.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

	<title>Twitter Tribe: {{ tribe.name }}</title>
	
</head>

<body>
    <div class='outermost'>
        <h1>{{ tribe.name }}</h1>
        <a href='{% url show_tribe tribe.slug %}'>View Tribe</a> - <a href='{% url show_tribe_terms tribe.slug %}'>Interest Terms</a>
        <form action="." method="get" accept-charset="utf-8">
            <p><label for="filter">Filter Results:</label><input type="text" name="filter" value="{{filter}}" id=""><input type="submit" value="Continue &rarr;"></p>
        </form>
        <div class='status_list'>
            <h2>Members' Status</h2>
            <ul>
                {% for s in status_list %}
                <li>
                    <ul>
                        <li class='profile_image'><img src='{{s.user.profile_image_url}}'/></li>
                        <li class='user'><a href='http://www.twitter.com/{{s.user.screen_name}}'>@{{ s.user.screen_name }}</a> - {{s.user.name}}</li>
                        <li class='status'>{{s.text}}</li>
                        <li class='date'>{{s.created_at}}</li>
                    </ul>
                </li>
                {% endfor %}
            </ul>
        </div>
        <div class='member_list'>
            <h3>{{ tribe.name }} Member List</h3>
            <ul>
                {% for m in tribe.member_set.all  %}
                    <li><a href='http://www.twitter.com/{{m.twitter_account}}'>@{{ m.twitter_account }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
</body>
</html>

twtribes/templates/twtribes/tribe_error.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

	<title>Twitter Tribe Error</title>
	
</head>

<body>
    <div class='outermost'>
        <h1>Twitter Tribes</h1>
        <h2>Unfortunately, there was an error</h2>
        <p>
            {{ error }}
        </p>
    </div>
</body>
</html>

twtribes/templates/twtribes/tribe_page.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

	<title>Twitter Tribe: {{ tribe.name }} - Page {{ page.title }}</title>
	
</head>

<body>
    <div class='outermost'>
        <h1>{{ tribe.name }}</h1>
        <a href='{% url show_tribe tribe.slug %}'>View Tribe</a> - <a href='{% url show_tribe_terms tribe.slug %}'>Interest Terms</a>
        <form action="." method="get" accept-charset="utf-8">
            <p><label for="filter">Filter Results:</label><input type="text" name="filter" value="{{filter}}" id=""><input type="submit" value="Continue &rarr;"></p>
        </form>
        
        <h2>Interest Pages</h2>
        <ul>
            {% for page in tribe.page_set.all %}
            <li>
                <a href="{% url show_tribe_page tribe.slug page.slug %}">{{ page.title }}</a>
            </li>
            {% endfor %}
        </ul>
        
        <div class='status_list'>
            <h2>{{ page.title }}:</h2>
            <p>{{ page.description }}</p>
            <ul>
                {% for s in results %}
                <li>
                    <ul>
                        <li class='status'><p>{{s.text|safe}}</p><span class='date'>{{s.created_at_as_datetime|timesince}} ago</span></li>
                        <li class='profile_image'><a href='http://www.twitter.com/{{s.from_user}}'><img width='48' src='{{s.profile_image_url}}'/></a></li>
                        <li class='user'><a href='http://www.twitter.com/{{s.from_user}}'>@{{ s.from_user }}</a></li>
                    </ul>
                </li>
                {% endfor %}
            </ul>
        </div>
        <div class='member_list'>
            <h3>{{ tribe.name }} Member List</h3>
            <ul>
                {% for m in tribe.member_set.all  %}
                    <li><a href='http://www.twitter.com/{{m.twitter_account}}'>@{{ m.twitter_account }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
</body>
</html>

twtribes/templates/twtribes/tribe_search.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

	<title>Twitter Tribe: {{ tribe.name }} - Interest Terms</title>
	
</head>

<body>
    <div class='outermost'>
        <h1>{{ tribe.name }}</h1>
        <a href='{% url show_tribe tribe.slug %}'>View Tribe</a> - <a href='{% url show_tribe_terms tribe.slug %}'>Interest Terms</a>
        <form action="." method="get" accept-charset="utf-8">
            <p><label for="filter">Filter Results:</label><input type="text" name="filter" value="{{filter}}" id=""><input type="submit" value="Continue &rarr;"></p>
        </form>
        
        <h2>Interest Pages</h2>
        <ul>
            {% for page in tribe.page_set.all %}
            <li>
                <a href="{% url show_tribe_page tribe.slug page.slug %}">{{ page.title }}</a>
            </li>
            {% endfor %}
        </ul>
        
        <div class='status_list'>
            <h2>Tribe Interest Terms:</h2>
            <ul>
                {% for s in results %}
                <li>
                    <ul>
                        <li class='status'><p>{{s.text|safe}}</p><span class='date'>{{s.created_at_as_datetime|timesince}} ago</span></li>
                        <li class='profile_image'><a href='http://www.twitter.com/{{s.from_user}}'><img width='48' src='{{s.profile_image_url}}'/></a></li>
                        <li class='user'><a href='http://www.twitter.com/{{s.from_user}}'>@{{ s.from_user }}</a></li>
                    </ul>
                </li>
                {% endfor %}
            </ul>
        </div>
        <div class='member_list'>
            <h3>{{ tribe.name }} Member List</h3>
            <ul>
                {% for m in tribe.member_set.all  %}
                    <li><a href='http://www.twitter.com/{{m.twitter_account}}'>@{{ m.twitter_account }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
</body>
</html>